### ISSUE TITLE
Unable to run faceidentification module. Error in loading submodule assets.src in specificwoker.py    

### ISSUE THREAD

**Issue by shubhMaheshwari** [robocomp/robocomp-robolab#48]
While installation and testing the face identification module, I am getting the following error. 

```python
SLICE_PATH environment variable was not exported. Using only the default paths
SLICE_PATH environment variable was not exported. Using only the default paths
('Trying', '/opt/robocomp/interfaces', 'to load FaceIdentification.ice')
('Using', '/opt/robocomp/interfaces', 'to load FaceIdentification.ice')
Traceback (most recent call last):
  File "src/faceidentification.py", line 65, in <module>
    from specificworker import *
  File "/home/shubh/robocomp/components/robocomp-robolab/components/detection/faceidentification/src/specificworker.py", line 35, in <module>
    import facenet2 as facenet
ImportError: No module named facenet2
```

The error is arising for the following code: 
https://github.com/robocomp/robocomp-robolab/blob/c7fe45cfe6de09e69378bac0d7a068e08ffdca17/components/detection/faceidentification/src/specificworker.py#L33

I am getting a similar error in another file: 
https://github.com/robocomp/robocomp-robolab/blob/c7fe45cfe6de09e69378bac0d7a068e08ffdca17/components/detection/test/faceidentificationclient/src/specificworker.py#L28

**Comment by shubhMaheshwari** [comment]
I have made a PR. Please have a look
